### ISSUE TITLE
Using the Chinese cloud - or not?

### ISSUE THREAD

**Issue by il77781** [like-a-freedom/home_assistant_qingping_air_wifi#1]
Hello! Sorry, but I didn't fully understand: Your integration still involves the use of a Chinese cloud, or you can use a customer private cloud (https://developer.qingping.co/main/private/device_private )?

**Comment by like-a-freedom** [comment]
Hello! It uses customer private cloud only. So the customer private cloud is needed to set up MQTT integration only. After integration, all communications between HA and Qingping Air will be via local MQTT.

**Comment by il77781** [comment]
Thank you! By the way, is this your article?
https://touch-max.ru/umnyj-dom/otvyazka-clear-grass-air-monitor-ot-oblaka-i-podklyuchenie-k-home-assistant

**Comment by like-a-freedom** [comment]
No, that's not my article.
But it can be used for configuration purposes.

**Comment by il77781** [comment]
Unfortunately, it is difficult for me to understand all the nuances myself... But still: Is there some other method in this article that is different from what was used in your integration? Or are there no fundamental differences, just in your integration, as far as I understand, everything is made a little easier for the average user?

**Comment by like-a-freedom** [comment]
This integration is via API, which means you need a permanent access to the Internet.
The integration described in the article is different, because it is local, i.e. the Internet is not required, which is an advantage. It is a bit more complicated, but not significantly so. The main thing there is to get access to the private cloud, the rest is not difficult to set up, in my opinion.

**Comment by il77781** [comment]
I've probably already wasted too much of your time, but still... But earlier you wrote that "all communications between HA and Qingping Air will be via local MQTT". And now you wrote that you need permanent access to the Internet... Something is not entirely clear... Or is access needed not for communications between HA and Qingping Air (this will happen locally), but for the functioning of this API?

**Comment by like-a-freedom** [comment]
Okay, let's try more structured:

- This integration (repository) — requires permanent internet connection
- [This article](https://touch-max.ru/umnyj-dom/otvyazka-clear-grass-air-monitor-ot-oblaka-i-podklyuchenie-k-home-assistant) is about local connection without internet (also you do not need the integration from the repo cause you can use out-of-the-box MQTT integration only)

**Comment by il77781** [comment]
And why does your integration need permanent Internet connection?
It gets from the Qingping Chinese cloud (or is it not a cloud?) some data (maybe a token), and then locally, using this received data, "communicates" with Qingping Air and receives air quality information from it? 
Or does Qingping Air send air quality data to the Qingping Chinese cloud, and then your integration takes it from there? 
Is any of the above at least close to the truth?)
And the method described in the article allows not to use the Qingping Chinese cloud at all, but to organize some such cloud locally... Right?

**Comment by like-a-freedom** [comment]
According to readme in the repo, this integration uses [public API](https://developer.qingping.co/main/guide/introduce) to get current states. That's why you have to provide permanent internet connection, obviously :)
Actually, I don't know which server the integration will use exactly — there is no information in public docs as I see.

> Or does Qingping Air send air quality data to the Qingping Chinese cloud, and then your integration takes it from there?

Sure thing! By default, Qingping sends data to the cloud, so that we can read it via public API mentioned above.

**Comment by il77781** [comment]
Yes, of course, what is obvious to you requires some more detailed pronouncing for me... ) I apologize again for wasting your time explaining obvious things...) I just got a little confused after reading this phrase in your first answer: "After integration, all communications between HA and Qingping Air will be via local MQTT". This phrase seems to be talking about getting air quality data without using non-local servers... That's why I thought (knowing absolutely nothing and not understanding about the public API) that your integration and the method described in the article are very similar... Now I understand that, apparently, there are significant differences... ).
However, initially I paid attention to your integration due to the fact that you had to use Qingping Air with WiFi. I would also like to use a connection via WiFi... But in this case, if I use the method described in the article, do I also need to change something there? After all, you have indicated that Qingping integration works with BLE by default... So I thought that this could also apply to the method described in the article...
